services:
  mongo-test:
    image: mongo:8.0.13-noble
    container_name: metis-mongo-test
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=metis-test
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express:latest
    container_name: metis-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-test
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo-test
    profiles:
      - debug

  redis-test:
    image: redis:6.0-alpine
    container_name: metis-redis-test
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
