server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: mackenzie-lms

  # Configuração do MongoDB
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/mackenzie_lms}
      auto-index-creation: true

  # Configuração do Redis (para blacklist de tokens)
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

  # Configuração OAuth2 Microsoft
  security:
    oauth2:
      client:
        registration:
          microsoft:
            client-id: ${MICROSOFT_CLIENT_ID}
            client-secret: ${MICROSOFT_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/v1.0/me
            user-info-authentication-method: header
            user-name-attribute: mail
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys

# Configurações JWT
app:
  jwt:
    secret: ${JWT_SECRET:mackenzieSecretKey2024!@#$%^&*()_+}
    expiration: ${JWT_EXPIRATION:86400000} # 24 horas em millisegundos

# Configurações de logging
logging:
  level:
    com.mackenzie.lms: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mackenzie-lms.log

# Configurações de CORS
cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Configurações da aplicação
mackenzie:
  lms:
    version: 1.0.0
    environment: ${APP_ENVIRONMENT:development}
    file:
      upload:
        max-size: 10MB
        allowed-types: pdf,docx,pptx,mp4,avi,mov
    security:
      jwt:
        blacklist:
          cleanup-interval: 3600000 # 1 hora em millisegundos